#!/bin/bash
replace=""

for f in $(ls -l | grep ^- | awk '{ print $10}')
do
  test $f = "install" && continue
  dest="$HOME/.$f"
  file="$PWD/$f"
  if [ -e $dest ] || [ -h $dest ]; then
    if [ "$replace" != "a" ]; then 
      echo "$dest already exists, replace? [y/n/a] "
      read replace
    fi
    if [ "$replace" = "a" ] || [ "$replace" = "y" ]; then
      echo "linking $file to $dest..."
      rm -f $dest
      ln -s $file $dest
      test "$replace" != "a" && replace=""
    else
      echo "skipping $file as it already exists..."
    fi
  else
    echo "linking $file to $dest..."
    ln -s $file $dest
  fi
done

ssh_config="$HOME/.ssh/config" 
if [ -e $ssh_config ] || [ -h $ssh_config ]; then
  echo "$ssh_config already exists, replace? [y/n] "
  read replace
  if [ "$replace" = "y" ]; then
    rm -f $ssh_config
    ln -s $PWD/ssh/config $ssh_config
  fi
else
  rm -f $ssh_config
  ln -s $PWD/ssh/config $ssh_config
fi
