#!/bin/sh

# svn functions

function svn_rm_missing {
  svn st | grep \! | awk '{ print $2}' | xargs svn rm
}

function svn_add_new {
  svn st | grep \? | awk '{ print $2}' | xargs svn add
}

# calculator
calc(){ awk "BEGIN{ print $* }" ;}
